"""nine migration.

Revision ID: 03fdb704cadd
Revises: 55ab928e4cdd
Create Date: 2020-12-01 03:08:12.578905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03fdb704cadd'
down_revision = '55ab928e4cdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('link', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car', 'link')
    # ### end Alembic commands ###
