"""Seven migration.

Revision ID: 55ab928e4cdd
Revises: 1eacc66cb4fc
Create Date: 2020-12-01 03:06:50.517913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55ab928e4cdd'
down_revision = '1eacc66cb4fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('license_plate', sa.String(length=140), nullable=True),
    sa.Column('brand', sa.String(length=140), nullable=True),
    sa.Column('condition_id', sa.String(length=140), nullable=True),
    sa.Column('on_go', sa.Integer(), nullable=True),
    sa.Column('price', sa.String(length=64), nullable=True),
    sa.Column('prod_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['on_go'], ['condition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('song')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('song',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('license_plate', sa.VARCHAR(length=140), nullable=True),
    sa.Column('brand', sa.VARCHAR(length=140), nullable=True),
    sa.Column('condition_id', sa.INTEGER(), nullable=True),
    sa.Column('on_go', sa.VARCHAR(length=64), nullable=True),
    sa.Column('price', sa.VARCHAR(length=64), nullable=True),
    sa.Column('prod_date', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['condition_id'], ['condition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('car')
    # ### end Alembic commands ###
