"""ten migration.

Revision ID: e0614528e0ad
Revises: 03fdb704cadd
Create Date: 2020-12-01 03:16:19.284177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0614528e0ad'
down_revision = '03fdb704cadd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('description', sa.String(length=640), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car', 'description')
    # ### end Alembic commands ###
